Repository ReScience/MLRC, pull requests merged in 2023-07, with the labels that each got.

#136 [2022] Paper 25
  2022/.DS_Store
  2022/25/LaViSE_phases.png
  2022/25/Makefile
  2022/25/README.md
  2022/25/ResNet-18-filter-output.png
  2022/25/appendix.tex
  2022/25/article.pdf
  2022/25/article.py
  2022/25/article.tex
  2022/25/bibliography.bib
  2022/25/content.tex
  2022/25/header.tex
  2022/25/metadata.tex
  2022/25/metadata.yaml
  2022/25/packages.tex
  2022/25/rescience.cls
  2022/25/roboto
  2022/25/source-code-pro
  2022/25/source-sans-pro
  2022/25/source-serif-pro
  2022/25/summary.tex
  2022/25/yaml-to-bibtex.py
  2022/25/yaml-to-latex.py
  2022/25/yaml-to-markdown.py
Labels: formatting

#120 [2022] Paper 16
  2022/16/.DS_Store
  2022/16/Makefile
  2022/16/README.md
  2022/16/appendix.tex
  2022/16/article.pdf
  2022/16/article.py
  2022/16/article.tex
  2022/16/bibliography.bib
  2022/16/content.tex
  2022/16/header.tex
  2022/16/images/Label-Free explainability.jpeg
  2022/16/images/PearsonCorrelationBetas.png
  2022/16/images/PearsonDsprites.png
  2022/16/images/PearsonMnist.png
  2022/16/images/Saliency-VAE.png
  2022/16/images/black horse.png
  2022/16/images/black pixels.png
  2022/16/images/blurred horse.png
  2022/16/images/cifar_densenet.png
  2022/16/images/example_consistency_cifar10.png
  2022/16/images/example_consistency_ecg.png
  2022/16/images/example_consistency_fmnist.png
  2022/16/images/example_consistency_mnist.png
  2022/16/images/feature_consistency.png
  2022/16/images/feature_consistency_cifar.png
  2022/16/images/feature_consistency_dense.png
  2022/16/images/feature_consistency_ecg5000.png
  2022/16/images/feature_consistency_fmnist.png
  2022/16/images/feature_consistency_mnist.png
  2022/16/images/pretext_saliency_integrated_grads.PNG
  2022/16/images/pretext_top_integrated_grads.PNG
  2022/16/images/roar_them.PNG
  2022/16/images/roar_us.PNG
  2022/16/images/saliency_Mnist.png
  2022/16/images/saliency_fmnist.png
  2022/16/images/saliency_maps_top_pretext_recon.PNG
  2022/16/images/saliency_pretext.PNG
  2022/16/images/sasliency_dsprites.png
  2022/16/images/top_example_pretext_recon.PNG
  2022/16/images/top_examples_fmnist.png
  2022/16/images/top_pretext.PNG
  2022/16/images/vae_integrated_grads.PNG
  2022/16/images/vae_integrated_grads_qualiative.PNG
  2022/16/metadata.tex
  2022/16/metadata.yaml
  2022/16/packages.tex
  2022/16/rescience.cls
  2022/16/roboto
  2022/16/source-code-pro
  2022/16/source-sans-pro
  2022/16/source-serif-pro
  2022/16/summary.tex
  2022/16/yaml-to-bibtex.py
  2022/16/yaml-to-latex.py
  2022/16/yaml-to-markdown.py
Labels: formatting

#119 [2022] Paper 15
  2022/15/.DS_Store
  2022/15/Makefile
  2022/15/README.md
  2022/15/appendix.tex
  2022/15/article.pdf
  2022/15/article.py
  2022/15/article.tex
  2022/15/bibliography.bib
  2022/15/content.tex
  2022/15/header.tex
  2022/15/images_and_figures/auc_clusters_gmm.png
  2022/15/images_and_figures/fairness_plots.png
  2022/15/images_and_figures/fpr1-2_clusters.png
  2022/15/images_and_figures/fpr1-3_clusters.png
  2022/15/images_and_figures/gmm_asian_men_older.pdf
  2022/15/images_and_figures/gmm_caucasian_blonde_females.pdf
  2022/15/images_and_figures/gmm_indian_men_mustache.pdf
  2022/15/images_and_figures/gmm_indian_women_young.pdf
  2022/15/images_and_figures/kmeans_african_males_sporty.pdf
  2022/15/images_and_figures/kmeans_asian_females_redhair.pdf
  2022/15/images_and_figures/kmeans_caucasian_males_shorthair.pdf
  2022/15/images_and_figures/kmeans_examples.png
  2022/15/images_and_figures/kmeans_indian_females.pdf
  2022/15/images_and_figures/violin_plots.png
  2022/15/metadata.tex
  2022/15/metadata.yaml
  2022/15/packages.tex
  2022/15/rescience.cls
  2022/15/roboto
  2022/15/source-code-pro
  2022/15/source-sans-pro
  2022/15/source-serif-pro
  2022/15/summary.tex
  2022/15/yaml-to-bibtex.py
  2022/15/yaml-to-latex.py
  2022/15/yaml-to-markdown.py
Labels: formatting

#158 [2022] Paper 36
  2022/36/Makefile
  2022/36/README.md
  2022/36/appendix.tex
  2022/36/article.pdf
  2022/36/article.py
  2022/36/article.tex
  2022/36/bibliography.bib
  2022/36/content.tex
  2022/36/header.tex
  2022/36/img/21879.jpg
  2022/36/img/3488.jpg
  2022/36/img/35313.jpg
  2022/36/img/38586.jpg
  2022/36/img/42482.jpg
  2022/36/img/42752.jpg
  2022/36/img/old1.png
  2022/36/img/old2.png
  2022/36/img/old3.png
  2022/36/img/young1.png
  2022/36/img/young2.png
  2022/36/img/young3.png
  2022/36/metadata.tex
  2022/36/metadata.yaml
  2022/36/packages.tex
  2022/36/rescience.cls
  2022/36/roboto
  2022/36/source-code-pro
  2022/36/source-sans-pro
  2022/36/source-serif-pro
  2022/36/summary.tex
  2022/36/yaml-to-bibtex.py
  2022/36/yaml-to-latex.py
  2022/36/yaml-to-markdown.py
Labels: compilation issue

#157 [2022] Paper 35
  2022/35/Makefile
  2022/35/README.md
  2022/35/appendix.tex
  2022/35/article.pdf
  2022/35/article.py
  2022/35/article.tex
  2022/35/bibliography.bib
  2022/35/content.tex
  2022/35/figures/original.pdf
  2022/35/figures/ours.pdf
  2022/35/header.tex
  2022/35/metadata.tex
  2022/35/metadata.yaml
  2022/35/packages.tex
  2022/35/rescience.cls
  2022/35/roboto
  2022/35/source-code-pro
  2022/35/source-sans-pro
  2022/35/source-serif-pro
  2022/35/summary.tex
  2022/35/yaml-to-bibtex.py
  2022/35/yaml-to-latex.py
  2022/35/yaml-to-markdown.py
Labels: compilation issue

#148 [2022] Paper 9
  2022/9/Makefile
  2022/9/README.md
  2022/9/appendix.tex
  2022/9/article.pdf
  2022/9/article.py
  2022/9/article.tex
  2022/9/bibliography.bib
  2022/9/content.tex
  2022/9/figures/figure-compare.pdf
  2022/9/figures/figure-rank.pdf
  2022/9/figures/figure-scale.pdf
  2022/9/header.tex
  2022/9/metadata.tex
  2022/9/metadata.yaml
  2022/9/packages.tex
  2022/9/rescience.cls
  2022/9/roboto
  2022/9/source-code-pro
  2022/9/source-sans-pro
  2022/9/source-serif-pro
  2022/9/summary.tex
  2022/9/yaml-to-bibtex.py
  2022/9/yaml-to-latex.py
  2022/9/yaml-to-markdown.py
Labels: compilation issue

#144 [2022] Paper 5
  2022/5/Makefile
  2022/5/README.md
  2022/5/appendix.tex
  2022/5/article.pdf
  2022/5/article.py
  2022/5/article.tex
  2022/5/bibliography.bib
  2022/5/content.tex
  2022/5/header.tex
  2022/5/metadata.tex
  2022/5/metadata.yaml
  2022/5/packages.tex
  2022/5/rescience.cls
  2022/5/results-appendix.tex
  2022/5/results-plots.tex
  2022/5/roboto
  2022/5/source-code-pro
  2022/5/source-sans-pro
  2022/5/source-serif-pro
  2022/5/summary.tex
  2022/5/yaml-to-bibtex.py
  2022/5/yaml-to-latex.py
  2022/5/yaml-to-markdown.py
Labels: compilation issue

#141 [2022] Paper 2
  2022/2/EFDM_Design.png
  2022/2/Makefile
  2022/2/README.md
  2022/2/appendix.tex
  2022/2/article.pdf
  2022/2/article.py
  2022/2/article.tex
  2022/2/bibliography.bib
  2022/2/content.tex
  2022/2/figures/efdm_fig1.png
  2022/2/figures/efdm_fig2.png
  2022/2/figures/efdm_fig3.png
  2022/2/figures/efdm_fig4.png
  2022/2/figures/efdm_fig5.png
  2022/2/header.tex
  2022/2/loss.png
  2022/2/metadata.tex
  2022/2/metadata.yaml
  2022/2/packages.tex
  2022/2/rescience.cls
  2022/2/roboto
  2022/2/source-code-pro
  2022/2/source-sans-pro
  2022/2/source-serif-pro
  2022/2/summary.tex
  2022/2/yaml-to-bibtex.py
  2022/2/yaml-to-latex.py
  2022/2/yaml-to-markdown.py
Labels: compilation issue

#133 [2022] Paper 21
  2022/21/Makefile
  2022/21/README.md
  2022/21/appendix.tex
  2022/21/article.pdf
  2022/21/article.py
  2022/21/article.tex
  2022/21/bibliography.bib
  2022/21/content.tex
  2022/21/header.tex
  2022/21/images/QualitativeResults1.png
  2022/21/images/QualitativeResults2.png
  2022/21/images/baseball.jpg
  2022/21/images/toothbrush.jpg
  2022/21/metadata.tex
  2022/21/metadata.yaml
  2022/21/packages.tex
  2022/21/rescience.cls
  2022/21/roboto
  2022/21/source-code-pro
  2022/21/source-sans-pro
  2022/21/source-serif-pro
  2022/21/summary.tex
  2022/21/yaml-to-bibtex.py
  2022/21/yaml-to-latex.py
  2022/21/yaml-to-markdown.py
Labels: compilation issue

#132 [2022] Paper 20
  2022/.DS_Store
  2022/20/Figures/Figure_2.png
  2022/20/Figures/Figure_2_parametersweep.png
  2022/20/Figures/Figure_2_parametersweep_age.png
  2022/20/Figures/Figure_3.png
  2022/20/Figures/Figure_3_Age.png
  2022/20/Figures/Figure_3_Occupation.png
  2022/20/Figures/Figure_3_parametersweep_age.png
  2022/20/Figures/Figure_3_parametersweep_gender.png
  2022/20/Figures/Figure_4_Age_0.png
  2022/20/Figures/Figure_4_Age_1.png
  2022/20/Figures/Figure_4_Age_2.png
  2022/20/Figures/Figure_4_Gender_0.png
  2022/20/Figures/Figure_4_Gender_1.png
  2022/20/Figures/Figure_4_Gender_2.png
  2022/20/Figures/Figure_4_Occupation_0.png
  2022/20/Figures/Figure_4_Occupation_1.png
  2022/20/Figures/Figure_4_Occupation_2.png
  2022/20/Figures/Figure_5.png
  2022/20/Figures/og_fig2.png
  2022/20/Figures/og_fig3.png
  2022/20/Figures/og_fig4.png
  2022/20/Makefile
  2022/20/README.md
  2022/20/appendix.tex
  2022/20/article.pdf
  2022/20/article.py
  2022/20/article.tex
  2022/20/bibliography.bib
  2022/20/content.tex
  2022/20/header.tex
  2022/20/metadata.tex
  2022/20/metadata.yaml
  2022/20/packages.tex
  2022/20/rescience.cls
  2022/20/roboto
  2022/20/source-code-pro
  2022/20/source-sans-pro
  2022/20/source-serif-pro
  2022/20/summary.tex
  2022/20/yaml-to-bibtex.py
  2022/20/yaml-to-latex.py
  2022/20/yaml-to-markdown.py
Labels: compilation issue

#127 [2022] Paper 40
  2022/40/Makefile
  2022/40/README.md
  2022/40/appendix.tex
  2022/40/article.pdf
  2022/40/article.py
  2022/40/article.tex
  2022/40/bibliography.bib
  2022/40/content.tex
  2022/40/header.tex
  2022/40/img/mae.pdf
  2022/40/img/mae_fonted.pdf
  2022/40/img/recon_row.pdf
  2022/40/img/reconstructions.pdf
  2022/40/metadata.tex
  2022/40/metadata.yaml
  2022/40/packages.tex
  2022/40/rescience.cls
  2022/40/roboto
  2022/40/source-code-pro
  2022/40/source-sans-pro
  2022/40/source-serif-pro
  2022/40/summary.tex
  2022/40/tables/mae_masking.tex
  2022/40/tables/results.tex
  2022/40/tables/smae_masking.tex
  2022/40/yaml-to-bibtex.py
  2022/40/yaml-to-latex.py
  2022/40/yaml-to-markdown.py
Labels: compilation issue

#125 [2022] Paper 38
  2022/38/Makefile
  2022/38/Moens/moens_diff_groups.pdf
  2022/38/Moens/moens_same_groups.pdf
  2022/38/Moens/synth5x_moon.pdf
  2022/38/MoonWalk/appendix_10grouped_diff.pdf
  2022/38/MoonWalk/appendix_10grouped_same.pdf
  2022/38/MoonWalk/appendix_3grouped.pdf
  2022/38/MoonWalk/appendix_5grouped.pdf
  2022/38/MoonWalk/results_10grouped_diff.pdf
  2022/38/MoonWalk/results_10grouped_same.pdf
  2022/38/MoonWalk/results_3grouped.pdf
  2022/38/MoonWalk/results_5grouped.pdf
  2022/38/README.md
  2022/38/appendix.tex
  2022/38/article.pdf
  2022/38/article.py
  2022/38/article.tex
  2022/38/bibliography.bib
  2022/38/content.tex
  2022/38/graph_walks.png
  2022/38/header.tex
  2022/38/influence_max_plots/IM_3grouped_own_graph.pdf
  2022/38/influence_max_plots/IM_ALL4.pdf
  2022/38/influence_max_plots/IM_rice_node2vec.pdf
  2022/38/link_prediction/link_prediction_rice_twitter.png
  2022/38/link_prediction/reproduced_linkpred_rice_twitter.pdf
  2022/38/metadata.tex
  2022/38/metadata.yaml
  2022/38/node_classification/NC_rice.pdf
  2022/38/packages.tex
  2022/38/rescience.cls
  2022/38/roboto
  2022/38/source-code-pro
  2022/38/source-sans-pro
  2022/38/source-serif-pro
  2022/38/summary.tex
  2022/38/synthx3_42.pdf
  2022/38/yaml-to-bibtex.py
  2022/38/yaml-to-latex.py
  2022/38/yaml-to-markdown.py
Labels: compilation issue

#123 [2022] Paper 14
  2022/14/.DS_Store
  2022/14/Makefile
  2022/14/README.md
  2022/14/appendix.tex
  2022/14/article.aux
  2022/14/article.bbl
  2022/14/article.bcf
  2022/14/article.blg
  2022/14/article.fdb_latexmk
  2022/14/article.fls
  2022/14/article.log
  2022/14/article.out
  2022/14/article.pdf
  2022/14/article.py
  2022/14/article.run.xml
  2022/14/article.tex
  2022/14/bibliography.bib
  2022/14/content.tex
  2022/14/figures/corr_comp.pdf
  2022/14/figures/model_score_comp.pdf
  2022/14/header.tex
  2022/14/metadata.tex
  2022/14/metadata.yaml
  2022/14/packages.tex
  2022/14/rescience.cls
  2022/14/roboto
  2022/14/source-code-pro
  2022/14/source-sans-pro
  2022/14/source-serif-pro
  2022/14/summary.tex
  2022/14/tool.png
  2022/14/yaml-to-bibtex.py
  2022/14/yaml-to-latex.py
  2022/14/yaml-to-markdown.py
Labels: compilation issue

#143 [2022] Paper 4
  2022/4/Makefile
  2022/4/README.md
  2022/4/appendix.tex
  2022/4/article.pdf
  2022/4/article.py
  2022/4/article.tex
  2022/4/bibliography.bib
  2022/4/content.tex
  2022/4/figures/DSpritesBoxPlot.png
  2022/4/figures/MNISTTCVAEBeta10.png
  2022/4/figures/MnistBoxPlot.png
  2022/4/figures/cifar10_consistency_features-1.jpg
  2022/4/figures/cifar10_similarity_rates-1.png
  2022/4/figures/dspritesbetavaebeta5.png
  2022/4/figures/ecg5000_consistency_features-1.jpg
  2022/4/figures/ecg5000_similarity_rates-1.png
  2022/4/figures/examples_CIFAR.png
  2022/4/figures/fact.drawio (1).png
  2022/4/figures/factsaliencymaps.drawio.png
  2022/4/figures/factsaliencymaps.png
  2022/4/figures/mnist_consistency_features-1.jpg
  2022/4/figures/original_CIFAR10.png
  2022/4/figures/similarity_rates-1.png
  2022/4/figures/top_examples (1).png
  2022/4/figures/top_examples.png
  2022/4/header.tex
  2022/4/metadata.tex
  2022/4/metadata.yaml
  2022/4/packages.tex
  2022/4/rescience.cls
  2022/4/roboto
  2022/4/source-code-pro
  2022/4/source-sans-pro
  2022/4/source-serif-pro
  2022/4/summary.tex
  2022/4/yaml-to-bibtex.py
  2022/4/yaml-to-latex.py
  2022/4/yaml-to-markdown.py
Labels: compilation issue, cleanup needed

#139 [2022] Paper 22
  2022/22/Figure 1.pdf
  2022/22/Makefile
  2022/22/README.md
  2022/22/appendix.tex
  2022/22/article.py
  2022/22/article.tex
  2022/22/bibliography.bib
  2022/22/content.tex
  2022/22/header.tex
  2022/22/metadata.tex
  2022/22/metadata.yaml
  2022/22/packages.tex
  2022/22/rescience.cls
  2022/22/roboto
  2022/22/source-code-pro
  2022/22/source-sans-pro
  2022/22/source-serif-pro
  2022/22/summary.tex
  2022/22/yaml-to-bibtex.py
  2022/22/yaml-to-latex.py
  2022/22/yaml-to-markdown.py
Labels: compilation issue, invalid

#137 [2022] Paper 26
  2022/26/Makefile
  2022/26/README.md
  2022/26/appendix.tex
  2022/26/article.pdf
  2022/26/article.py
  2022/26/article.tex
  2022/26/bibliography.bib
  2022/26/content.tex
  2022/26/header.tex
  2022/26/images/bert-age-old-young.png
  2022/26/images/bertft-vs-bertpre.jpg
  2022/26/images/fine-pre.jpeg
  2022/26/images/young-old.jpeg
  2022/26/metadata.tex
  2022/26/metadata.yaml
  2022/26/packages.tex
  2022/26/rescience.cls
  2022/26/roboto
  2022/26/source-code-pro
  2022/26/source-sans-pro
  2022/26/source-serif-pro
  2022/26/summary.tex
  2022/26/yaml-to-bibtex.py
  2022/26/yaml-to-latex.py
  2022/26/yaml-to-markdown.py
Labels: compilation issue, invalid
